# -*- coding: utf-8 -*-
"""streamlit run app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wbac9Bh1HRGVI85VmrYA-yVW1b-Wix4h
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV
from sklearn.metrics import mean_squared_error, r2_score

# ==========================================
# Page Configuration
# ==========================================
st.set_page_config(page_title="Property Price Optimization", layout="wide")

# ==========================================
# Data Loading (Cached for performance)
# ==========================================
@st.cache_data
def load_data():
    try:
        # Assuming the CSV is in the same directory as this script
        df = pd.read_csv("housing_ridge_lasso_dataset.csv")
        return df
    except FileNotFoundError:
        return None

df = load_data()

# ==========================================
# Sidebar Navigation
# ==========================================
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["1. Project Overview", "2. Exploratory Data Analysis (EDA)", "3. Model Training (Ridge/Lasso)", "4. Analytical Q&A"])

# Display error if data is missing
if df is None and page != "4. Analytical Q&A":
    st.error("⚠️ Dataset not found! Please ensure 'housing_ridge_lasso_dataset.csv' is in the same directory as this script.")
    st.stop()

# ==========================================
# PAGE 1: Project Overview
# ==========================================
if page == "1. Project Overview":
    st.title("🏡 Property Price Optimization via Regularized Regression")
    st.markdown("""
    This application demonstrates the end-to-end machine learning pipeline for predicting house prices using **Ridge (L2)** and **Lasso (L1)** Regularization.

    ### Dataset Glimpse
    """)
    st.dataframe(df.head())

    st.markdown("### Dataset Statistics")
    st.dataframe(df.describe())

# ==========================================
# PAGE 2: Exploratory Data Analysis (EDA)
# ==========================================
elif page == "2. Exploratory Data Analysis (EDA)":
    st.title("📊 Exploratory Data Analysis")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Target Variable Distribution (House Price)")
        fig_dist, ax_dist = plt.subplots(figsize=(8, 5))
        sns.histplot(df['house_price'], kde=True, ax=ax_dist, color='blue')
        ax_dist.set_title("Distribution of House Prices")
        st.pyplot(fig_dist)

    with col2:
        st.subheader("Multicollinearity Check")
        st.markdown("Notice the high correlation between variables like `median_income` & `income_index`.")

    st.subheader("Correlation Heatmap")
    fig_corr, ax_corr = plt.subplots(figsize=(14, 10))
    corr_matrix = df.corr()
    sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", ax=ax_corr, cbar=True)
    st.pyplot(fig_corr)

# ==========================================
# PAGE 3: Model Training
# ==========================================
elif page == "3. Model Training (Ridge/Lasso)":
    st.title("⚙️ Model Training & Evaluation")

    st.markdown("### 1. Data Preprocessing")
    st.write("Separating features (X) and target (y), applying Train-Test Split, and performing Standard Scaling.")

    # Preprocessing
    X = df.drop('house_price', axis=1)
    y = df['house_price']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    st.success("Data successfully split and scaled!")

    # Model Training
    st.markdown("### 2. Training Models")

    # OLS
    lr = LinearRegression()
    lr.fit(X_train_scaled, y_train)
    lr_pred = lr.predict(X_test_scaled)

    # Ridge
    ridge = RidgeCV(alphas=np.logspace(-3, 3, 100), cv=5)
    ridge.fit(X_train_scaled, y_train)
    ridge_pred = ridge.predict(X_test_scaled)

    # Lasso
    lasso = LassoCV(alphas=np.logspace(-3, 3, 100), cv=5, max_iter=10000)
    lasso.fit(X_train_scaled, y_train)
    lasso_pred = lasso.predict(X_test_scaled)

    # Metrics Calculation
    metrics = {
        "Model": ["Standard OLS", "Ridge (L2)", "Lasso (L1)"],
        "R-Squared": [
            r2_score(y_test, lr_pred),
            r2_score(y_test, ridge_pred),
            r2_score(y_test, lasso_pred)
        ],
        "RMSE": [
            np.sqrt(mean_squared_error(y_test, lr_pred)),
            np.sqrt(mean_squared_error(y_test, ridge_pred)),
            np.sqrt(mean_squared_error(y_test, lasso_pred))
        ]
    }

    metrics_df = pd.DataFrame(metrics)
    st.table(metrics_df.style.format({"R-Squared": "{:.4f}", "RMSE": "{:.2f}"}))

    st.markdown(f"**Optimal Ridge Alpha:** {ridge.alpha_:.4f}  |  **Optimal Lasso Alpha:** {lasso.alpha_:.4f}")

    # Coefficient Comparison
    st.markdown("### 3. Feature Selection: Coefficient Comparison")
    st.write("Notice how Lasso shrinks certain coefficients (like redundant indices) to exactly **Zero**.")

    coef_df = pd.DataFrame({
        'Feature': X.columns,
        'OLS Coef': lr.coef_,
        'Ridge Coef': ridge.coef_,
        'Lasso Coef': lasso.coef_
    })

    st.dataframe(coef_df.style.background_gradient(cmap='viridis', subset=['Ridge Coef', 'Lasso Coef']))

# ==========================================
# PAGE 4: Analytical Q&A
# ==========================================
elif page == "4. Analytical Q&A":
    st.title("💡 Analytical Questions & Answers")

    # This is exactly matching the content requested
    st.markdown("""
# Housing Analysis: Analytical Questions & Answers

### 1. What indicators in the dataset suggest the presence of multicollinearity?

Looking at the **Correlation Heatmap**, you can see very high correlation values (near 1.0) between variables like `median_income` and `income_index`, or `square_footage` and `living_area_index`. When two or more variables tell the "same story," it indicates multicollinearity.

### 2. Why might Ordinary Least Squares (OLS) regression perform poorly in this scenario?

OLS tries to find the best fit by looking at every variable equally. When you have multicollinearity (like the variables mentioned above), OLS becomes "unstable." It struggles to decide which variable is actually responsible for the price change, leading to wildly fluctuating coefficients and poor predictions on new data.

### 3. How would you detect overfitting in the baseline model?

You compare the model's performance on the **Training Data** vs. the **Test Data**. If your $R^2$ is very high (e.g., 0.95) on the training data but much lower (e.g., 0.70) on the test data, the model has "memorized" the noise in the training set rather than learning general patterns. This gap is a clear sign of overfitting.

### 4. What is the conceptual difference between L1 and L2 regularization?

* **L1 (Lasso):** Think of this as a "Slayer." It can shrink a coefficient all the way to **zero**, effectively removing that variable from the model.

* **L2 (Ridge):** Think of this as a "Shrinker." It reduces the size of coefficients but **never** makes them exactly zero. It keeps all variables but minimizes their impact.

### 5. How does Ridge regression affect coefficient magnitude compared to OLS?

Ridge regression adds a penalty based on the square of the coefficients. This forces the coefficients to be **smaller (closer to zero)** than they would be in OLS. It "mutes" the variables so that no single variable has an unfairly large influence on the price prediction.

### 6. Why does Lasso regression perform feature selection?

Because Lasso uses the absolute value of the coefficients in its penalty (L1), the mathematical "shape" of this penalty has sharp corners at zero. During optimization, it often hits these corners, forcing less important variables (like redundant indices) to have a coefficient of **exactly 0.0**, essentially "selecting" only the best features.

### 7. Which model would you prefer if interpretability is more important?

**Lasso Regression.** Because Lasso removes useless or redundant variables (by setting them to zero), you end up with a shorter, simpler list of factors that actually affect the house price. It is much easier to explain 5 key drivers to a client than 17 overlapping ones.

### 8. How does feature scaling influence Ridge and Lasso results?

Regularization penalizes the *size* of the coefficients. If `median_income` is in the tens of thousands and `bedrooms` is a single digit, the model will unfairly penalize the income variable just because its numbers are bigger. **Scaling** ensures all variables are on the same playing field (e.g., 0 to 1) so the penalty is applied fairly.

### 9. What happens when the regularization parameter (λ) is very large?

* As $\lambda$ (Alpha) increases, the penalty becomes heavier.

* The coefficients shrink closer and closer to zero.

* The model becomes **simpler** but potentially **underfits** (it becomes too "lazy" to learn the actual patterns in the data).

### 10. Can removing correlated variables manually be an alternative to regularization?

**Yes, but it's less efficient.** You could manually drop `income_index` if you already have `median_income`. However, in complex datasets with hundreds of variables, doing this manually is difficult and prone to human error. Regularization (especially Lasso) does this automatically and mathematically determines which variable is better to keep based on the actual target data.
    """)